# Generated by Django 5.2.7 on 2025-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(choices=[('elementary', '초등'), ('middle', '중등'), ('high', '고등')], help_text='학교급', max_length=20)),
                ('output_type', models.CharField(choices=[('notice', '가정통신문'), ('pdf', 'PDF')], help_text='산출물 유형', max_length=20)),
                ('theme', models.CharField(choices=[('fire_safety', '화재'), ('general_safety', '일반')], help_text='테마', max_length=50)),
                ('prompt', models.TextField(blank=True, help_text='생성된 프롬프트', null=True)),
                ('response_text', models.TextField(blank=True, help_text='LLM 응답 원본', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_pdfs/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('error', 'error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
