# Generated by Django 5.2.7 on 2025-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='output_type',
            field=models.CharField(choices=[('notice', '가정통신문'), ('pdf', '교육자료'), ('field_trip', '현장체험학습')], help_text='산출물 유형', max_length=20),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='prompt',
            field=models.TextField(blank=True, help_text='AI 모델에 전달된 최종 프롬프트', null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='response_text',
            field=models.TextField(blank=True, help_text='AI 모델로부터 받은 응답 (HTML 형식)', null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='school_level',
            field=models.CharField(blank=True, choices=[('elementary', '초등'), ('middle', '중등'), ('high', '고등')], help_text='학교급 (초등/중등/고등)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='theme',
            field=models.CharField(help_text='안전교육 테마 또는 현장체험학습 장소명', max_length=100),
        ),
    ]
